const cities = [
  { label: "AD-Andorra La Vella" },
  { label: "AE-Abu Dhabi" },
  { label: "AE-Dubai" },
  { label: "AF-Kabul" },
  { label: "AI-The Valley" },
  { label: "AL-Tirana" },
  { label: "AM-Yerevan" },
  { label: "AO-Luanda" },
  { label: "AR-Buenos Aires" },
  { label: "AR-Cordoba" },
  { label: "AR-Rosario" },
  { label: "AS-Pago Pago" },
  { label: "AT-Vienna" },
  { label: "AU-Adelaide" },
  { label: "AU-Brisbane" },
  { label: "AU-Canberra" },
  { label: "AU-Gold Coast" },
  { label: "AU-Hobart" },
  { label: "AU-Melbourne" },
  { label: "AU-Perth" },
  { label: "AU-Sydney" },
  { label: "AW-Oranjestad" },
  { label: "AZ-Baku" },
  { label: "BA-Sarajevo" },
  { label: "BB-Bridgetown" },
  { label: "BD-Chittagong" },
  { label: "BD-Dhaka" },
  { label: "BD-Khulna" },
  { label: "BE-Brussels" },
  { label: "BF-Ouagadougou" },
  { label: "BG-Sofia" },
  { label: "BH-Manama" },
  { label: "BI-Bujumbura" },
  { label: "BJ-Porto-novo" },
  { label: "BM-Hamilton" },
  { label: "BN-Bandar Seri Begawan" },
  { label: "BO-La Paz" },
  { label: "BO-Santa Cruz de la Sierra" },
  { label: "BR-Belo Horizonte" },
  { label: "BR-Brasilia" },
  { label: "BR-Fortaleza" },
  { label: "BR-Rio de Janeiro" },
  { label: "BR-Salvador" },
  { label: "BR-Sao Paulo" },
  { label: "BS-Nassau" },
  { label: "BT-Thimphu" },
  { label: "BW-Gaborone" },
  { label: "BY-Minsk" },
  { label: "BZ-Belmopan" },
  { label: "CA-Calgary" },
  { label: "CA-Edmonton" },
  { label: "CA-Halifax" },
  { label: "CA-Mississauga" },
  { label: "CA-Montreal" },
  { label: "CA-Ottawa" },
  { label: "CA-Quebec City" },
  { label: "CA-Regina" },
  { label: "CA-Saskatoon" },
  { label: "CA-St. John's-05" },
  { label: "CA-Toronto" },
  { label: "CA-Vancouver" },
  { label: "CA-Victoria" },
  { label: "CA-Winnipeg" },
  { label: "CD-Kinshasa" },
  { label: "CD-Lubumbashi" },
  { label: "CF-Bangui" },
  { label: "CG-Brazzaville" },
  { label: "CH-Bern" },
  { label: "CH-Geneva" },
  { label: "CH-Zurich" },
  { label: "CI-Abidjan" },
  { label: "CI-Yamoussoukro" },
  { label: "CK-Avarua" },
  { label: "CL-Santiago" },
  { label: "CM-Douala" },
  { label: "CM-Yaounde" },
  { label: "CN-Beijing" },
  { label: "CN-Chengdu" },
  { label: "CN-Chongqing" },
  { label: "CN-Guangzhou" },
  { label: "CN-Harbin" },
  { label: "CN-Kaifeng" },
  { label: "CN-Lanzhou" },
  { label: "CN-Nanchong" },
  { label: "CN-Nanjing" },
  { label: "CN-Puyang" },
  { label: "CN-Shanghai" },
  { label: "CN-Shenyang" },
  { label: "CN-Shenzhen" },
  { label: "CN-Shiyan" },
  { label: "CN-Tai'an" },
  { label: "CN-Tianjin" },
  { label: "CN-Wuhan" },
  { label: "CN-Xi'an" },
  { label: "CN-Yueyang" },
  { label: "CN-Zhumadian" },
  { label: "CO-Barranquilla" },
  { label: "CO-Bogota" },
  { label: "CO-Cali" },
  { label: "CO-Medellin" },
  { label: "CR-San José" },
  { label: "CU-Havana" },
  { label: "CV-Praia" },
  { label: "CW-Willemstad" },
  { label: "CY-Nicosia" },
  { label: "CZ-Prague" },
  { label: "DE-Berlin" },
  { label: "DE-Hamburg" },
  { label: "DE-Munich" },
  { label: "DK-Copenhagen" },
  { label: "DM-Roseau" },
  { label: "DO-Santiago de los Caballeros" },
  { label: "DO-Santo Domingo" },
  { label: "DZ-Algiers" },
  { label: "EC-Guayaquil" },
  { label: "EC-Quito" },
  { label: "EE-Tallinn" },
  { label: "EG-Al Jizah" },
  { label: "EG-Alexandria" },
  { label: "EG-Cairo" },
  { label: "ER-Asmara" },
  { label: "ES-Barcelona" },
  { label: "ES-Madrid" },
  { label: "ET-Addis Ababa" },
  { label: "FI-Helsinki" },
  { label: "FJ-Suva" },
  { label: "FK-Stanley" },
  { label: "FO-Tórshavn" },
  { label: "FR-Marseilles" },
  { label: "FR-Paris" },
  { label: "GA-Libreville" },
  { label: "GB-Belfast" },
  { label: "GB-Birmingham" },
  { label: "GB-Bristol" },
  { label: "GB-Cardiff" },
  { label: "GB-Edinburgh" },
  { label: "GB-Glasgow" },
  { label: "GB-Leeds" },
  { label: "GB-Liverpool" },
  { label: "GB-London" },
  { label: "GB-Manchester" },
  { label: "GB-Sheffield" },
  { label: "GE-Tbilisi" },
  { label: "GH-Accra" },
  { label: "GH-Kumasi" },
  { label: "GI-Gibraltar" },
  { label: "GL-Nuuk" },
  { label: "GM-Banjul" },
  { label: "GN-Camayenne" },
  { label: "GN-Conakry" },
  { label: "GQ-Malabo" },
  { label: "GR-Athens" },
  { label: "GT-Guatemala City" },
  { label: "GW-Bissau" },
  { label: "GY-Georgetown" },
  { label: "HK-Hong Kong" },
  { label: "HN-Tegucigalpa" },
  { label: "HR-Zagreb" },
  { label: "HT-Port-au-Prince" },
  { label: "HU-Budapest" },
  { label: "ID-Bandung" },
  { label: "ID-Bekasi" },
  { label: "ID-Depok" },
  { label: "ID-Jakarta" },
  { label: "ID-Makassar" },
  { label: "ID-Medan" },
  { label: "ID-Palembang" },
  { label: "ID-Semarang" },
  { label: "ID-South Tangerang" },
  { label: "ID-Surabaya" },
  { label: "ID-Tangerang" },
  { label: "IE-Dublin" },
  { label: "IL-Ashdod" },
  { label: "IL-Ashkelon" },
  { label: "IL-Bat Yam" },
  { label: "IL-Be'er Sheva" },
  { label: "IL-Beit Shemesh" },
  { label: "IL-Bnei Brak" },
  { label: "IL-Eilat" },
  { label: "IL-Hadera" },
  { label: "IL-Haifa" },
  { label: "IL-Herzliya" },
  { label: "IL-Holon" },
  { label: "IL-Jerusalem" },
  { label: "IL-Kfar Saba" },
  { label: "IL-Lod" },
  { label: "IL-Modiin" },
  { label: "IL-Nazareth" },
  { label: "IL-Netanya" },
  { label: "IL-Petach Tikvah" },
  { label: "IL-Ra'anana" },
  { label: "IL-Ramat Gan" },
  { label: "IL-Ramla" },
  { label: "IL-Rishon LeZion" },
  { label: "IL-Tel Aviv" },
  { label: "IL-Tiberias" },
  { label: "IM-Douglas" },
  { label: "IN-Ahmadabad" },
  { label: "IN-Bangalore" },
  { label: "IN-Bombay" },
  { label: "IN-Calcutta" },
  { label: "IN-Chennai" },
  { label: "IN-Cochin" },
  { label: "IN-Hyderabad" },
  { label: "IN-Jaipur" },
  { label: "IN-Kanpur" },
  { label: "IN-New Delhi" },
  { label: "IN-Pune" },
  { label: "IN-Surat" },
  { label: "IQ-Baghdad" },
  { label: "IR-Tehran" },
  { label: "IS-Reykjavík" },
  { label: "IT-Milano" },
  { label: "IT-Rome" },
  { label: "JM-Kingston" },
  { label: "JO-Amman" },
  { label: "JP-Kobe-shi" },
  { label: "JP-Kyoto" },
  { label: "JP-Nagoya-shi" },
  { label: "JP-Osaka-shi" },
  { label: "JP-Sapporo" },
  { label: "JP-Tokyo" },
  { label: "KE-Nairobi" },
  { label: "KG-Bishkek" },
  { label: "KH-Phnom Penh" },
  { label: "KM-Moroni" },
  { label: "KN-Basseterre" },
  { label: "KP-Pyongyang" },
  { label: "KR-Busan" },
  { label: "KR-Seoul" },
  { label: "KW-Kuwait" },
  { label: "KY-George Town" },
  { label: "KZ-Almaty" },
  { label: "KZ-Astana" },
  { label: "LA-Vientiane" },
  { label: "LB-Beirut" },
  { label: "LC-Castries" },
  { label: "LI-Vaduz" },
  { label: "LR-Monrovia" },
  { label: "LS-Maseru" },
  { label: "LT-Vilnius" },
  { label: "LU-Luxemburg" },
  { label: "LV-Riga" },
  { label: "LY-Tripoli" },
  { label: "MA-Casablanca" },
  { label: "MA-Rabat" },
  { label: "MD-Chisinau" },
  { label: "ME-Podgorica" },
  { label: "MG-Antananarivo" },
  { label: "MK-Skopje" },
  { label: "ML-Bamako" },
  { label: "MM-Mandalay" },
  { label: "MM-Rangoon" },
  { label: "MN-Ulaanbaatar" },
  { label: "MP-Saipan" },
  { label: "MR-Nouakchott" },
  { label: "MS-Plymouth" },
  { label: "MT-Valletta" },
  { label: "MU-Port Louis" },
  { label: "MW-Lilongwe" },
  { label: "MX-Cancun" },
  { label: "MX-Guadalajara" },
  { label: "MX-Iztapalapa" },
  { label: "MX-Mazatlan" },
  { label: "MX-Mexico City" },
  { label: "MX-Monterrey" },
  { label: "MX-Puerto Vallarta" },
  { label: "MX-Tijuana" },
  { label: "MY-Kota Bharu" },
  { label: "MY-Kuala Lumpur" },
  { label: "MZ-Maputo" },
  { label: "NA-Windhoek" },
  { label: "NC-Nouméa" },
  { label: "NE-Niamey" },
  { label: "NG-Abuja" },
  { label: "NG-Lagos" },
  { label: "NI-Managua" },
  { label: "NL-Amsterdam" },
  { label: "NO-Oslo" },
  { label: "NP-Kathmandu" },
  { label: "NU-Alofi" },
  { label: "NZ-Auckland" },
  { label: "NZ-Christchurch" },
  { label: "NZ-Wellington" },
  { label: "OM-Muscat" },
  { label: "PA-Panama City" },
  { label: "PE-Lima" },
  { label: "PF-Papeete" },
  { label: "PG-Port Moresby" },
  { label: "PH-Manila" },
  { label: "PK-Islamabad" },
  { label: "PK-Karachi" },
  { label: "PL-Warsaw" },
  { label: "PR-San Juan" },
  { label: "PT-Lisbon" },
  { label: "PY-Asuncion" },
  { label: "QA-Doha" },
  { label: "RO-Bucharest" },
  { label: "RS-Belgrade" },
  { label: "RU-Moscow" },
  { label: "RU-Novosibirsk" },
  { label: "RU-Saint Petersburg" },
  { label: "RU-Yekaterinburg" },
  { label: "RW-Kigali" },
  { label: "SA-Jeddah" },
  { label: "SA-Mecca" },
  { label: "SA-Medina" },
  { label: "SA-Riyadh" },
  { label: "SB-Honiara" },
  { label: "SC-Victoria" },
  { label: "SD-Khartoum" },
  { label: "SD-Omdurman" },
  { label: "SE-Stockholm" },
  { label: "SG-Singapore" },
  { label: "SH-Jamestown" },
  { label: "SI-Ljubljana" },
  { label: "SK-Bratislava" },
  { label: "SL-Freetown" },
  { label: "SN-Dakar" },
  { label: "SO-Mogadishu" },
  { label: "SR-Paramaribo" },
  { label: "ST-São Tomé" },
  { label: "SV-San Salvador" },
  { label: "SY-Aleppo" },
  { label: "SY-Damascus" },
  { label: "SZ-Mbabane" },
  { label: "TC-Cockburn Town" },
  { label: "TD-Ndjamena" },
  { label: "TG-Lomé" },
  { label: "TH-Bangkok" },
  { label: "TJ-Dushanbe" },
  { label: "TM-Ashgabat" },
  { label: "TN-Tunis" },
  { label: "TR-Adana" },
  { label: "TR-Ankara" },
  { label: "TR-Bursa" },
  { label: "TR-Istanbul" },
  { label: "TR-Izmir" },
  { label: "TV-Funafuti" },
  { label: "TW-Kaohsiung" },
  { label: "TW-Taipei" },
  { label: "TZ-Dar es Salaam" },
  { label: "TZ-Dodoma" },
  { label: "UA-Kharkiv" },
  { label: "UA-Kiev" },
  { label: "UG-Kampala" },
  { label: "US-Atlanta-GA" },
  { label: "US-Austin-TX" },
  { label: "US-Baltimore-MD" },
  { label: "US-Boston-MA" },
  { label: "US-Buffalo-NY" },
  { label: "US-Chicago-IL" },
  { label: "US-Cincinnati-OH" },
  { label: "US-Cleveland-OH" },
  { label: "US-Columbus-OH" },
  { label: "US-Dallas-TX" },
  { label: "US-Denver-CO" },
  { label: "US-Detroit-MI" },
  { label: "US-Hartford-CT" },
  { label: "US-Honolulu-HI" },
  { label: "US-Houston-TX" },
  { label: "US-Lakewood-NJ" },
  { label: "US-Las Vegas-NV" },
  { label: "US-Livingston-NY" },
  { label: "US-Los Angeles-CA" },
  { label: "US-Memphis-TN" },
  { label: "US-Miami-FL" },
  { label: "US-Milwaukee-WI" },
  { label: "US-Monsey-NY" },
  { label: "US-New Haven-CT" },
  { label: "US-New York-NY" },
  { label: "US-Omaha-NE" },
  { label: "US-Orlando-FL" },
  { label: "US-Passaic-NJ" },
  { label: "US-Philadelphia-PA" },
  { label: "US-Phoenix-AZ" },
  { label: "US-Pittsburgh-PA" },
  { label: "US-Portland-OR" },
  { label: "US-Providence-RI" },
  { label: "US-Richmond-VA" },
  { label: "US-Rochester-NY" },
  { label: "US-Saint Louis-MO" },
  { label: "US-Saint Paul-MN" },
  { label: "US-San Diego-CA" },
  { label: "US-San Francisco-CA" },
  { label: "US-Seattle-WA" },
  { label: "US-Silver Spring-MD" },
  { label: "US-Teaneck-NJ" },
  { label: "US-Washington-DC" },
  { label: "US-White Plains-NY" },
  { label: "UY-Montevideo" },
  { label: "UZ-Tashkent" },
  { label: "VC-Kingstown" },
  { label: "VE-Caracas" },
  { label: "VE-Maracaibo" },
  { label: "VE-Maracay" },
  { label: "VE-Valencia" },
  { label: "VG-Road Town" },
  { label: "VN-Hanoi" },
  { label: "VN-Ho Chi Minh City" },
  { label: "WS-Apia" },
  { label: "YE-Sanaa" },
  { label: "YT-Mamoudzou" },
  { label: "ZA-Cape Town" },
  { label: "ZA-Durban" },
  { label: "ZA-Johannesburg" },
  { label: "ZA-Pretoria" },
  { label: "ZM-Lusaka" },
  { label: "ZW-Harare" },
];

export default cities;
